### ISSUE TITLE
Allow URL for self-hosted VDO ninja

### ISSUE THREAD

**Issue by saschafoerster** [bitfocus/companion-module-vdo-ninja#17]
We are hosting a copy of VDO ninja on our own servers and would like to be able to add that domain.

**Comment by bryce-seifert** [comment]
@saschafoerster Are you able to confirm, does the self-hosted version still have websockets on port 443
Ie would the url format wss://`your-url.com`:443 work?

**Comment by saschafoerster** [comment]
@bryce-seifert Websockets should be on port 443, yes. 
Of course, the domain for the web socket can be different between installations: 
- Easiest way is to keep using the websocket of Steve:  wss://wss.vdo.ninja/
- More advanced people can use piesocket 
- Or you can also self host (seemingly a less secure) version of websockets yourself, provided by Steve: https://github.com/steveseguin/websocket_server

The Index.html of VDO ninja has a configuration for the web socket: 
https://github.com/steveseguin/vdo.ninja/blob/d0e0d7e04d987d877509a5ee95e720a8f4048d37/index.html#L2604

```
session.wss = "wss://wss.contribute.cam:443";
session.customWSS = true;
```
I hope this answers your question. :)  Thank you for the quick reply.

**Comment by bryce-seifert** [comment]
@saschafoerster This should now be possible in the latest beta. Let me know if you run into any issues

**Comment by saschafoerster** [comment]
Finally had time to check it, @bryce-seifert. What I meant is, I would like to use my self hosted version of VDO Ninja, so not only the domain of the web socket is changed, but the whole domain of VDO Ninja needs an option. :) 
We could use https://vdo.bonn.digital (just an example) for the studio and https://wss.bonn.digital for the web socket-server (separately). :) Thank you anyway for your work! :)

**Comment by bryce-seifert** [comment]
@saschafoerster That should be possible. You would just event the wss URL in the config (as in the screenshot below). The module only directly communicates to the websocket server, not the host domain for VDO Ninja or any custom service.

If you have a specific websocket URL you're having issues with, please feel free to send it to me and I can test it.

<img width="707" alt="Screenshot 2024-02-25 at 10 53 21 AM" src="https://github.com/bitfocus/companion-module-vdo-ninja/assets/50299051/575cad87-edd7-4708-96a5-900491bb8910">

**Comment by saschafoerster** [comment]
I tried it with a self hosted Bitfocus Companion on my own VDO installation, on the VDO.ninja installation and here: https://companion.vdo.ninja/
I wasn't able to trigger anything. Sorry, if it works for you but might it be, that it is a general problem?

**Comment by bryce-seifert** [comment]
Do you see any errors in the companion log?

does the module show as connected or is there an error?

**Comment by saschafoerster** [comment]
If I use the regular web socket (just an API code), then I get an timeout: 
<img width="662" alt="Bildschirmfoto 2024-02-26 um 16 27 22" src="https://github.com/bitfocus/companion-module-vdo-ninja/assets/1153741/7e2d5a8e-ec10-4706-a7db-db2c7a8945f3">
If I try another web socket domain, I got "No connection" in the logs (but then my whole raspberry killed itself)

**Comment by bryce-seifert** [comment]
That’s very odd. If you open the module logs (the > icon located next to the connection name) and have that open while starting the connection, does it provide any more descriptive errors?

**Comment by saschafoerster** [comment]
@bryce-seifert Sorry, it was my fault. Got it working, I had some network issues. Thank you very much for your patience!

**Comment by bryce-seifert** [comment]
No worries, glad it is resolved!
